language: php
php:
  - 5.6
  - 7.0

git:
  depth: 1

env:
  - SYMFONY_VERSION="3.1.*" DB=mysql

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

notifications:
  email: false
  